#!/usr/bin/env bash

set -uexo pipefail

sed -i 's|#LockLayering.*|LockLayering=true|' /etc/rpm-ostreed.conf

dnf -y install qemu-guest-agent

dnf -y install zram-generator-defaults

dnf -y install firewalld fail2ban
sed -i 's|DefaultZone=public|DefaultZone=custom|' /etc/firewalld/firewalld.conf

dnf -y install tmux vim fish tree
dnf -y install systemd-container # for machinectl

env --chdir=/ctx/rootfiles/quadlets/funkwhale ./setup
