#!/usr/bin/env bash

set -uexo pipefail

sed -i 's|#LockLayering.*|LockLayering=true|' /etc/rpm-ostreed.conf

dnf -y install qemu-guest-agent

dnf -y install zram-generator-defaults

dnf -y install fail2ban

dnf -y install tmux vim fish tree
dnf -y install systemd-container # for machinectl

for m in /ctx/modules/*/ ; do
    env --chdir="$m" ./build
done
