#!/usr/bin/env bash

set -uexo pipefail

install -Dm644 -t /etc/containers/systemd/users/1000 units/*

install -Dm644 ./funkwhale.env -t /etc/funkwhale
install -Dm644 ./funkwhale-nginx.template -t /etc/funkwhale
install -Dm644 ./funkwhale_proxy.conf -t /etc/funkwhale
