#!/usr/bin/env bash

useradd --system --shell /usr/bin/bash --home-dir /var/home/funkwhale funkwhale
FUNKWHALE_UID=$(id -u funkwhale)

install -Dm644 sysusers.conf /usr/lib/sysusers.d/funkwhale.conf
install -Dm644 tmpfiles.conf /usr/lib/tmpfiles.d/funkwhale.conf

mkdir -p /usr/share/containers/systemd/users/$FUNKWHALE_UID
cp units/* /usr/share/containers/systemd/users/$FUNKWHALE_UID/
cp funkwhale.env /etc
